name: WorkFlow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install mypy
      run: pip install mypy

    - name: Type check
      run: mypy ./server/py/dog.py

    - name: Test with pytest
      run: |
        pip install pytest
        pytest ./test/test_dog.py

    - name: Run benchmarks
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        python ./benchmark/benchmark_dog.py
